### ISSUE TITLE
Make test

### ISSUE THREAD

**Issue by gharib85** [sunqm/libcint#104]
I used mingw in windows 
I was able to run Julia examples
But python was unable to load library 
I found this warning in read me 
But I don't know how to handle it 
How can edit cmake file ?

**Comment by sunqm** [comment]
If you mean the error of MKL library, this is not caused by this integral library. This library does not use MKL library.

**Comment by gharib85** [comment]
Finally done
The problem was related to windows 
Ctybes.cdll.libraryload
Can't loadlibrary
Using CDLL then pass argtypes


_cint=ctypes.CDLL(path to ......ibcint.dll)


CINTcgto_spheric=_cint.CINTcgto_spheric
CINTcgto_spheric.restype = ctypes.c_int
CINTcgto_spheric.argtypes = [ctypes.c_int, numpy.ctypeslib.ndpointer(dtype=numpy.intc, ndim=2)]
di = CINTcgto_spheric(0, bas)
dj = CINTcgto_spheric(1, bas)


cint1e_ipnuc_sph=_cint.cint1e_ipnuc_sph
cint1e_ipnuc_sph.argtypes = [
    numpy.ctypeslib.ndpointer(dtype=numpy.double, ndim=3),
    (ctypes.c_int * 2),
    numpy.ctypeslib.ndpointer(dtype=numpy.intc, ndim=2),
    ctypes.c_int,
    numpy.ctypeslib.ndpointer(dtype=numpy.intc, ndim=2),
    ctypes.c_int,
    numpy.ctypeslib.ndpointer(dtype=numpy.double, ndim=1)
]
buf = numpy.empty((di, dj, 3), order='F')
cint1e_ipnuc_sph(buf, (ctypes.c_int * 2)(0, 1), atm, atm.shape[0], bas, bas.shape[1], env)
print(buf)
