### ISSUE TITLE
N-e integrals 

### ISSUE THREAD

**Issue by JangidBhavnesh** [sunqm/libcint#109]
In cint lib, the Nuclear-electron 1e integrals consider which type of nuclear modal?
1. Point charges
2. Finite nuclei {Gaussian type}

**Comment by sunqm** [comment]
1. point charge by default.
2. You can set `atm[:,2]` to 2 and corresponding env for Gaussian nuclear charge model. The relevant code is here https://github.com/sunqm/libcint/blob/master/src/g1e.c#L194

**Comment by JangidBhavnesh** [comment]
Thanks
