### ISSUE TITLE
Angular momentum integral

### ISSUE THREAD

**Issue by JangidBhavnesh** [sunqm/libcint#110]
Is it possible to calculate the angular momentum integral with libcint?

For example, I have highly paramagnetic TM-Complex, where the unpair electrons are localized on metal center, then using that as origin, can I calculate the 1e integrals in presence of magnetic field?

**Comment by sunqm** [comment]
No, integrals with magnetic field is not supported. You can instead compute the angular momentum integrals, such as `int1e_cg_irxp` https://github.com/sunqm/libcint/blob/master/scripts/auto_intor.cl#L12 . Then adjust the phase and multiply to the magnetic fields.

**Comment by JangidBhavnesh** [comment]
Okay.

Thanks

**Comment by JangidBhavnesh** [comment]
I have follow-up question here:  

To include the picture change corrections in 1e property integrals, like dipole moment or angular momentum integral, I am looking for the 'pOp' type integrals (O is the corresponding property operator).

For the dipole moment, based on PySCF documentation and examples, I think those integrals are 'int1e_sprsp'.  However, for the  
angular momentum integrals, I have not found the 'int1e_cg_spirxpsp' type integrals. Do you know if I can compute these integrals via Libcint?

Thanks

**Comment by JangidBhavnesh** [comment]
I have written the expression of the above integral as described [here](https://github.com/sunqm/libcint?tab=readme-ov-file#generating-integrals), and was able to compute these integrals using Libcint.

`"int1e_cg_spirxpsp"         (#C(0 1) sigma dot p \| rc cross p \| sigma dot p))`

Is there a test that I can do to make sure these integrals are correct? 

I tried to compute the $$\langle L^2_{PC} \rangle$$ for a CAS wave function, and they were different from the $$\langle L^2_{NR}\rangle$$ but that doesn't prove or disprove it.

`Test-system`
Al atom, ground-state $${}^2\mathrm{P}$$ state: Hence L-value will be 1. For the NR case, I got the 1, but the picture change corrected $$\langle L^2_{PC}\rangle$$, I got 0.999, I don't know whether that is right!.
