### ISSUE TITLE
How to rescale coefficients

### ISSUE THREAD

**Issue by chstem** [sunqm/libcint#22]
I am trying to get the correct one- and two-electron integrals for some cartesian basis functions. But I cannot find any information on how libcint expects the coefficients to be scaled.

Currently I am rescaling my coefficients to include the normalization factor, so the contracted basis functions are directly normalized. After passing these to libcint I calculate the overlap (`cint1e_ovlp_cart`). 

For d functions I get for the self overlaps: `1.0000   0.3333   0.3333   1.0000   0.3333   1.0000`. `1.0` is fine, but there has to be something wrong with `0.3333`.

For s and p functions all the integrals look fine, **if I divide** the coefficients additionally by  `0.282094791773878143` and `0.488602511902919921` (taken from pyscf's `cart2sph`). But that is just trial and error based, and does not tell me how it should really work.

Could you elaborate how I am supposed to proceed from the normalized contractions?

**Comment by sunqm** [comment]
Shortly the contraction coefficients required by libcint code is the product of normal contraction coefficients (defined in basis data base) times the Gaussian normalization factor (returned by the CINTgto_norm function). Hope the following examples could make it more clear.

1. the example of C interface here
https://github.com/sunqm/libcint/blob/master/examples/c_call_spheric.c#L57

2. the basis set from emsl
 #BASIS SET: (3s) -> [1s]
 H    S
       3.42525091             0.15432897
       0.62391373             0.53532814
       0.16885540             0.44463454

```
from pyscf import gto
mol = gto.M(atom='H 0 0 0', basis=sto3g, spin=1)
# _atm _bas and _env are the arguments actually being passed to libcint
print mol._atm
print mol._bas
print mol._env
for i in range(mol.nbas):
    print mol.bas_ctr_coeff(i)  # the contraction coefficients associated to the normalized GTOs, corresponding to the data from emsl basis library
for i in range(mol.nbas):
    print mol._libcint_ctr_coeff(i)  # the contraction coefficients actually fed to libcint
```

**Comment by sunqm** [comment]
The library does not support normalization coefficients for cartesian Gaussians. You have to scale the integrals with the diagonal elements of overlap matrix.

**Comment by chstem** [comment]
Thank you, I got it working now.
