### ISSUE TITLE
Implement GTG Integrals

### ISSUE THREAD

**Issue by jordangarside** [sunqm/libcint#23]
@sunqm We are interested in using and implementing the Gaussian type geminal integrals below.

![equation](http://latex.codecogs.com/gif.latex?e^{-\lambda&space;(r_{12})^2})

![equation](http://latex.codecogs.com/gif.latex?\frac{e^{-\lambda&space;(r_{12})^2}}{r_{12}})

We would like to use these integrals to separate out long and short range Coulomb interaction.

These integrals have been widely used in previous F12 calculations, and we know that the they are implemented in the [libint package](https://github.com/evaleev/libint) by Ed Valeev. 

We assume that this would be easy to implement in libcint. We are open to implementing these integrals ourselves, but it might be very little effort for you to implement them.

Is this something you would be interested in? Or, do you any suggestions for us to implement them?

**Comment by sunqm** [comment]
It's not difficult to implement the two integrals.  Particularly, the second integral can be implemented quickly with small modification to the code.

**Comment by jordangarside** [comment]
I got the coul_gtg integrals working in PySCF after your commit today.

Thanks Qiming!

**Comment by jordangarside** [comment]
Also I'm not sure if it's better to have the GTG integrals in the same file as the other F12 methods (STG and YP), since they're all F12 integrals.

The environment variables (`PTR_F12_ZETA` and `PTR_GTG_ZETA`) and naming conventions (`g2e_f12` and  `g2e_gtg`) may confuse people down the road.

**Comment by sunqm** [comment]
I don't recommend to use this function for now.  It does not yet fully agree to
the tests by numerical integration.

Qiming
On Thu, Oct 05, 2017 at 04:51:51PM -0700, Jordan Garside wrote:
> I got the coul_gtg integrals working in PySCF after your commit today.
> 
> Thanks Qiming!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Dr. Qiming Sun
Division of Chemistry and Chemical Engineering
California Institute of Technology
www.sunqm.net

**Comment by jordangarside** [comment]
Ok, thanks for the heads up.

**Comment by sunqm** [comment]
will not supported in released version
