### ISSUE TITLE
Derivatives of rinv operator

### ISSUE THREAD

**Issue by Melisius** [sunqm/libcint#29]
Hi,

I am included in a project where we want to implement Polarizable Embedding in PySCF. 
For this we field, field-gradient, .. integrals. 

I have tried to  add these integrals through the auto_intor.cl script by adding:

     '("inte1e_d1rinv"              (\| nabla rinv |\))
     '("inte1e_d2rinv"              (\| nabla nabla rinv |\))

To the "grad1.c" section. 
The code compiles and gives a result in PySCF, but it differs alot from the result that I get if I do a finite difference with "int1e_rinv".
The finite difference is simply done as:

    step = 10**-5
    mol.set_rinv_orig((step,0,0))
    rinvp = mol.intor("int1e_rinv")
    mol.set_rinv_orig((-step,0,0))
    rinvm = mol.intor("int1e_rinv")
    field_finite = (rinvp - rinvm)/(2*step)

I have also tried to use the "nabla-rinv" operator in auto_intor.cl, by adding:

     '("inte1e_d1rinv2"              (\| nabla-rinv |\))

This yield a compilation error:

    /home/kjellgren/libcint/src/autocode/grad1.c: In function ‘CINTgout1e_int1e_d1rinv2’:
    /home/kjellgren/libcint/src/autocode/grad1.c:487:9: error: ‘g2’ undeclared (first use in this function); 
    did you mean ‘g1’?
    G1E_D_I(g2, g0, envs->i_l+0, envs->j_l+0, 0);

Also it dosen't quite lead to the field-gradient integrals.

To get the field, field-gradient, ... integrals, what would be the correct operators to use in the auto_intor.cl? Seem like "nabla rinv" gives something else than I expect.

**Comment by sunqm** [comment]
The high order derivatives over operator 1/r were not implemented. The first order derivative can be evaluated with the partial integration
<i | \nabla 1/r | j > = -< \nabla i | 1/r | j > - < i | 1/r | \nabla j >

The relevant code in pyscf is
```Python
-mol.intor('int1e_iprinv') - mol.intor('int1e_iprinv').transpose(0,2,1)
```

Applying the partial integration twice, the second order derivative can be calculated as
https://github.com/sunqm/pyscf/blob/dev/pyscf/prop/efg/rhf.py#L169

**Comment by juanjoaucar** [comment]
Dear libcint developers,

I need some high order derivatives over operator 1/r :
![image](https://user-images.githubusercontent.com/93452131/171699302-548b4078-b8a1-446f-b47e-06be1b8b0aec.png)

(q_zz is the z derivative of the z component of the electric field)

How can I construct them?
Thanks in advance,
Juan J.
