### ISSUE TITLE
Some file went into /usr/usr/lib64/ instead of /usr/lib64/

### ISSUE THREAD

**Issue by kevinsmia1939** [sunqm/libcint#42]
Hello,

I am trying to package libcint 3.1.1 to openSUSE.
https://build.opensuse.org/package/show/home:andythe_great/libcint

I have found that some file go to /usr/usr/lib64/ directory. As shown below.

```
/usr/usr/lib64/libcint.so.3.1.1
/usr/usr/lib64/libcint.so.3
/usr/usr/lib64/libcint.so
```

I then patch CMakeLists.txt (fix_lib_install_dir.patch in the repo) like this,	
```
-install(TARGETS cint DESTINATION "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}" COMPONENT "lib")
+install(TARGETS cint DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT "lib")
```
Which fix the issue, the file now go to /usr/lib64/ normally.
Is this an issue? 

Thank you.

**Comment by sunqm** [comment]
It's strange. Normally, https://github.com/sunqm/libcint/blob/master/CMakeLists.txt#L20 GNUInstalsDirs should be able to place the files in the right directories. I'd let GUNInstallDirs figure out these paths than hardcode the settings. In latest release, I remove these lines from CMakeList.txt

**Comment by kevinsmia1939** [comment]
Thanks, I will close this for now and if the issue persist I will open a new ticket.
