### ISSUE TITLE
3c1e overlap integrals

### ISSUE THREAD

**Issue by ambmax00** [sunqm/libcint#45]
Hi,
Is there a way to compute 3-centre 1-electron overlap integrals using libcint/qcint?
Is it the function `int3c1e_sph`?

**Comment by sunqm** [comment]
The function is int3c1e_ovlp

On Sun, Oct 25, 2020 at 08:58:04AM -0700, Maximilien Ambroise wrote:
> Hi,
> Is there a way to compute 3-centre 1-electron overlap integrals using libcint/qcint?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/45

--

**Comment by ambmax00** [comment]
I can only find `CINTg3c1e_ovlp`, but I cannot find any function with the name `int3c1e_ovlp`. Can you maybe point out where it is in the code?

**Comment by sunqm** [comment]
There are three relevant functions
int3c1e_cart
int3c1e_sph
int3c1e_spinor

On Sun, Oct 25, 2020 at 06:33:04PM -0700, Maximilien Ambroise wrote:
> I can only find `CINTg3c1e_ovlp`, but I cannot find any function with the name `int3c1e_ovlp`. Can you maybe point out where it is in the code?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/45#issuecomment-716254778

--

**Comment by ambmax00** [comment]
Ok, I have it figured out, but I still get an error when calling the function. Here's the valgrind output:
````
==249877== Invalid write of size 4
==249877==    at 0x32976A: CINTOpt_non0coeff_byshell (optimizer.c:463)
==249877==    by 0x33A8F2: CINT3c1e_loop_nopt (cint3c1e.c:84)
==249877==    by 0x33C842: CINT3c1e_spheric_drv (cint3c1e.c:494)
==249877==    by 0x33CA41: int3c1e_sph (cint3c1e.c:588)
==249877==    by 0x33CE56: cint3c1e_sph (cint3c1e.c:652)
==249877==    ....
==249877==    by 0x2BA2A1: ints::aoloader::compute() (aoloader.cpp:458)
==249877==  Address 0xc569c88 is 0 bytes after a block of size 88 alloc'd
==249877==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==249877==    by 0x33C926: CINT3c1e_spheric_drv (cint3c1e.c:485)
==249877==    by 0x33CA41: int3c1e_sph (cint3c1e.c:588)
==249877==    by 0x33CE56: cint3c1e_sph (cint3c1e.c:652)
==249877==    ....
==249877==    by 0x2266B9: fock::fockmod::init() (fock_builder.cpp:160)
````

**Comment by ambmax00** [comment]
Nevermind, it was already fixed with the latest commit, thanks!
