### ISSUE TITLE
Derivatives of 1/r12 operator

### ISSUE THREAD

**Issue by LetyX** [sunqm/libcint#46]
Does libcint have integrals of 1/r12 derivatives or is it possible to add them using the integral generator? I know there is a nabla-rinv operator for 1-electron integrals, but as far as I can see there is no 2-electron equivalent.

**Comment by sunqm** [comment]
It can be derived using partial integration. Here is an example based on pyscf
```
# d/d x_1 (ij|kl)
int = mol.intor('int2e_ip1', comp=3)
int + int.transpose(0,2,1,3,4)
```

On Mon, Oct 26, 2020 at 10:02:12AM -0700, LetyX wrote:
> Does libcint have integrals of 1/r12 derivatives or is it possible to add them using the integral generator? I know there is a nabla-rinv operator for 1-electron integrals, but as far as I can see there is no 2-electron equivalent.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/46

--

**Comment by LetyX** [comment]
Thank you for the answer! On a related note, I noticed some integrals in auto_intor.cl have the operator nabla-r12.
Does that correspond to the first derivative of 1/r12? Presumably the first derivative of r12 would just be 1 or -1, unless I'm missing something.

**Comment by sunqm** [comment]
It has sign -1. It actually computes `\vec{r12} / |r12|^3`
