### ISSUE TITLE
libcint 4.0.5 tests fail on x86 and x86_64

### ISSUE THREAD

**Issue by susilehtola** [sunqm/libcint#47]
Trying to update the Fedora package of libcint to 4.0.5, I ran into test failures on both x86 and x86_64 architectures:
```
Checking test dependency graph end
test 1
    Start 1: cinttest
1: Test command: /usr/bin/python3.9 "/builddir/build/BUILD/libcint-4.0.5/testsuite/test_cint.py" "--quick"
1: Test timeout computed to be: 10000000
1/2 Test #1: cinttest .........................***Failed    2.15 sec
```
The builds, however, succeed on armv7hl, aarch64, and s390x architectures.

Build logs on the failing architectures
[i386.log](https://github.com/sunqm/libcint/files/5471262/i386.log)
[x86_64.log](https://github.com/sunqm/libcint/files/5471263/x86_64.log)

**Comment by susilehtola** [comment]
> Can confirm. I had similar issues with 4.0.3 & 4.0.5. 

Yours might be a different issue then, since 4.0.3 builds without problems in Fedora - clean tests on all architectures.

**Comment by sunqm** [comment]
Might be related to a bug fixed in 4.0.6

On Sun, Nov 01, 2020 at 08:08:18AM -0800, Susi Lehtola wrote:
> Trying to update the Fedora package of libcint to 4.0.5, I ran into test failures on both x86 and x86_64 architectures:
> ```
> Checking test dependency graph end
> test 1
>     Start 1: cinttest
> 1: Test command: /usr/bin/python3.9 "/builddir/build/BUILD/libcint-4.0.5/testsuite/test_cint.py" "--quick"
> 1: Test timeout computed to be: 10000000
> 1/2 Test #1: cinttest .........................***Failed    2.15 sec
> ```
> The builds, however, succeed on armv7hl, aarch64, and s390x architectures.
> 
> Build logs on the failing architectures
> [i386.log](https://github.com/sunqm/libcint/files/5471262/i386.log)
> [x86_64.log](https://github.com/sunqm/libcint/files/5471263/x86_64.log)
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/47

--

**Comment by susilehtola** [comment]
OK, I'll give it a try.

The versions of libcint and qcint appear to have fallen out of sync. Is this intentional?

**Comment by sunqm** [comment]
No. Just too many updates and fixes recently caused the two libraries a little
bit diverged. Will match them in the future.

On Sat, Nov 14, 2020 at 12:28:58PM -0800, Susi Lehtola wrote:
> OK, I'll give it a try.
> 
> The versions of libcint and qcint appear to have fallen out of sync. Is this intentional?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/47#issuecomment-727261152

--

**Comment by susilehtola** [comment]
Great. We can mark this solved.
