### ISSUE TITLE
Integration into vcpkg lead to syntax errors

### ISSUE THREAD

**Issue by Hendiadyoin1** [sunqm/libcint#49]
I'm trying to get this library into vcpkg and while compiling the library through their pipleine I encounter a lot of syntax errors, could be a problem with their pipeline though.

vcpkg issue:  
[link](https://github.com/microsoft/vcpkg/issues/15315)

The following is the output log (partially in german):  
[config-x64-windows-out.log](https://github.com/sunqm/libcint/files/5743095/config-x64-windows-out.log)

**Comment by linquize** [comment]
MSVC complex number support is very different from gcc.
MSVC uses `_Dcomplex` instead of `double complex`

MSVC
```c
_Dcomplex d = { 1, 2 };
```

gcc
```c
double complex d = 1 + 2 * _Complex_I;
```

**Comment by Hendiadyoin1** [comment]
I've tried converting the code to accommodate the compiler differences, but i still get lots of errors, and not all of them seem to be related to the complex implementation.

My attempts can be found in my fork of the repo

**Comment by Hendiadyoin1** [comment]
after some googling I might be able to resolve the errors if you would like to move to cpp instead of plain c.

List of Errors still active:
- complex numbers cant be multiplied inplace using msvc's implementation due to it being a struct
- implicit conversion to comlex not possible and will require a lot of refactoring in the cart2sph.c file for example
- some arrays seem to be 0-sized (compiler does not like that)
- other arrays have an unknown size

**Comment by sunqm** [comment]
It's a c project. It cannot be compiled with c++ compiler. The code follows c89
standard plus the a few features of c99 (variable-length array and inline comment).
I guess you may need to specify a compilation flag like -std=c99 in the build
pipeline.

On Sat, Dec 26, 2020 at 04:57:48AM -0800, Hendiadyoin1 wrote:
> I'm trying to get this library into vcpkg and while compiling the library through their pipleine I encounter a lot of syntax errors, could be a problem with their pipeline though.
> 
> vcpkg issue:  
> [link](https://github.com/microsoft/vcpkg/issues/15315)
> 
> The following is the output log (partially in german):  
> [config-x64-windows-out.log](https://github.com/sunqm/libcint/files/5743095/config-x64-windows-out.log)
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/49

--

**Comment by sunqm** [comment]
I'm not sure about complex number. For other issues, c compiler should work
correctly.

On Sat, Dec 26, 2020 at 10:38:15AM -0800, Hendiadyoin1 wrote:
> after some googling I might be able to resolve the errors if you would like to move to cpp instead of plain c.
> 
> List of Errors still active:
> - complex numbers cant be multiplied inplace using msvc's implementation due to it being a struct
> - implicit conversion to comlex not possible and will require a lot of refactoring in the cart2sph.c file for example
> - some arrays seem to be 0-sized (compiler does not like that)
> - other arrays have an unknown size
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/49#issuecomment-751384186

--

**Comment by linquize** [comment]
even if switch to C99 standard, MSVC's complex number differs from gcc.

**Comment by Hendiadyoin1** [comment]
So due to that vast incopatability, I've looked into converting the code to cpp and got to the linker stage, but apperantly the implementation of ```dgemm_(...)``` is missing.

**Comment by sunqm** [comment]
It's a BLAS function. You can use openblas or mkl if available.

On Sun, Jan 03, 2021 at 02:15:46PM -0800, Hendiadyoin1 wrote:
> So due to that vast incopatability, I've looked into converting the code to cpp and got to the linker stage, but apperantly the implementation of ```dgemm_(...)``` is missing.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/49#issuecomment-753683799

--

**Comment by Hendiadyoin1** [comment]
I've got it to compile under msvc, could you check if everything is still the way it should be?  
The repository can be found [here](https://github.com/Hendiadyoin1/libcxxint)

**Comment by sunqm** [comment]
The new release 5.* changes the way to handle complex numbers. The real and imaginary parts of a complex number is treated as two number continues in memory.
