### ISSUE TITLE
libcint::rys_roots negative value in sqrt for roots 2 (j=2)

### ISSUE THREAD

**Issue by ambmax00** [sunqm/libcint#51]
Hi,
When I am computing short range coulomb integrals with PTR_RANGE_OMEGA = - 0.1 for example, I get the following error(s):
````
libcint::rys_roots negative value in sqrt for roots 2 (j=2)
libcint::rys_roots negative value in sqrt for roots 3 (j=3)
libcint::rys_roots negative value in sqrt for roots 2 (j=2)
etc...
````
It worked in version 4.0.7, but no longer works since 60d233f7951552c93dd1c9fa390c298158f56f0c

**Comment by sunqm** [comment]
Do you have a test example for this error?

On Fri, Feb 26, 2021 at 04:03:19AM -0800, Maximilien Ambroise wrote:
> Hi,
> When I am computing short range coulomb integrals with PTR_RANGE_OMEGA = - 0.1 for example, I get the following error(s):
> ````
> libcint::rys_roots negative value in sqrt for roots 2 (j=2)
> libcint::rys_roots negative value in sqrt for roots 3 (j=3)
> libcint::rys_roots negative value in sqrt for roots 2 (j=2)
> etc...
> ````
> It worked in version 4.0.7, but no longer works since 60d233f7951552c93dd1c9fa390c298158f56f0c
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/51

--

**Comment by ambmax00** [comment]
Here is a minimal example:
````
#include <cint.h>

int cint2c2e_sph(double *out, const int *shls,
	const int *atm, int natm, const int *bas, int nbas, const double *env,
	const CINTOpt *opt);

int main() {

	int atoms[1000];
	double env[1000];
	int bas[1000];

	env[PTR_RANGE_OMEGA] = -0.1;
	int off = PTR_ENV_START;

	// H2O
	int natoms = 3;

	atoms[0 * ATM_SLOTS + CHARGE_OF] = 8;
	atoms[0 * ATM_SLOTS + PTR_COORD] = off;

	env[off++] = 0.0;
	env[off++] = 0.0;
	env[off++] = 0.222591;

	atoms[1 * ATM_SLOTS + CHARGE_OF] = 1;
        atoms[1 * ATM_SLOTS + PTR_COORD] = off;

	env[off++] = 0.0;
        env[off++] = 1.42759;
        env[off++] = -0.890363;

	atoms[1 * ATM_SLOTS + CHARGE_OF] = 1;
        atoms[1 * ATM_SLOTS + PTR_COORD] = off;

        env[off++] = 0.0;
        env[off++] = -1.42759;
        env[off++] = -0.890363;

	// add two example shells which give the error
	// from the cc-pVDZ-jkfit basis set for density fitting
	
	int nbas = 2;
	
	bas[0 * BAS_SLOTS + ATOM_OF] = 0;
	bas[0 * BAS_SLOTS + ANG_OF] = 3;
	bas[0 * BAS_SLOTS + NPRIM_OF] = 1;
	bas[0 * BAS_SLOTS + NCTR_OF] = 1;
	bas[0 * BAS_SLOTS + PTR_EXP] = off;

	env[off++] = 4.22194; //exponent
	env[off++] = 50.3979; // normalized con. coeff.

	bas[1 * BAS_SLOTS + ATOM_OF] = 1;
        bas[1 * BAS_SLOTS + ANG_OF] = 1;
        bas[1 * BAS_SLOTS + NPRIM_OF] = 1;
        bas[1 * BAS_SLOTS + NCTR_OF] = 1;
        bas[1 * BAS_SLOTS + PTR_EXP] = off;

	env[off++] = 1.91496;
	env[off++] = 6.57181;

	int shls[2] = {0,1};

	double buf[1000];

	// compute the 2c2e integrals in the erfc-metric
	cint2c2e_sph(buf, shls, atoms, natoms, bas, nbas, env, 0);
	return 0;

}
````
I am computing the 2c2e erfc-attenuated coulomb integrals for an auxiliary basis set. The contraction coefficients are normalized in this example.

**Comment by sunqm** [comment]
The contraction coefficients in your code were not initialized

```
bas[0 * BAS_SLOTS + PTR_COEFF]
bas[1 * BAS_SLOTS + PTR_COEFF]
```

On Sun, Feb 28, 2021 at 11:38:56PM -0800, Maximilien Ambroise wrote:
> Here is a minimal example:
> ````
> #include <cint.h>
> 
> int cint2c2e_sph(double *out, const int *shls,
> 	const int *atm, int natm, const int *bas, int nbas, const double *env,
> 	const CINTOpt *opt);
> 
> int main() {
> 
> 	int atoms[1000];
> 	double env[1000];
> 	int bas[1000];
> 
> 	env[PTR_RANGE_OMEGA] = -0.1;
> 	int off = PTR_ENV_START;
> 
> 	// H2O
> 	int natoms = 3;
> 
> 	atoms[0 * ATM_SLOTS + CHARGE_OF] = 8;
> 	atoms[0 * ATM_SLOTS + PTR_COORD] = off;
> 
> 	env[off++] = 0.0;
> 	env[off++] = 0.0;
> 	env[off++] = 0.222591;
> 
> 	atoms[1 * ATM_SLOTS + CHARGE_OF] = 1;
>         atoms[1 * ATM_SLOTS + PTR_COORD] = off;
> 
> 	env[off++] = 0.0;
>         env[off++] = 1.42759;
>         env[off++] = -0.890363;
> 
> 	atoms[1 * ATM_SLOTS + CHARGE_OF] = 1;
>         atoms[1 * ATM_SLOTS + PTR_COORD] = off;
> 
>         env[off++] = 0.0;
>         env[off++] = -1.42759;
>         env[off++] = -0.890363;
> 
> 	// add two example shells which give the error
> 	// from the cc-pVDZ-jkfit basis set for density fitting
> 	
> 	int nbas = 2;
> 	
> 	bas[0 * BAS_SLOTS + ATOM_OF] = 0;
> 	bas[0 * BAS_SLOTS + ANG_OF] = 3;
> 	bas[0 * BAS_SLOTS + NPRIM_OF] = 1;
> 	bas[0 * BAS_SLOTS + NCTR_OF] = 1;
> 	bas[0 * BAS_SLOTS + PTR_EXP] = off;
> 
> 	env[off++] = 4.22194; //exponent
> 	env[off++] = 50.3979; // normalized con. coeff.
> 
> 	bas[1 * BAS_SLOTS + ATOM_OF] = 1;
>         bas[1 * BAS_SLOTS + ANG_OF] = 1;
>         bas[1 * BAS_SLOTS + NPRIM_OF] = 1;
>         bas[1 * BAS_SLOTS + NCTR_OF] = 1;
>         bas[1 * BAS_SLOTS + PTR_EXP] = off;
> 
> 	env[off++] = 1.91496;
> 	env[off++] = 6.57181;
> 
> 	int shls[2] = {0,1};
> 
> 	double buf[1000];
> 
> 	// compute the 2c2e integrals in the erfc-metric
> 	cint2c2e_sph(buf, shls, atoms, natoms, bas, nbas, env, 0);
> 	return 0;
> 
> }
> ````
> I am computing the 2c2e erfc-attenuated coulomb integrals for an auxiliary basis set. The contraction coefficients are normalized in this example.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/51#issuecomment-787727154

--

**Comment by ambmax00** [comment]
I updated the code, but the error is still there
