### ISSUE TITLE
src/cint3c2e.c:756: possible infinite recursion

### ISSUE THREAD

**Issue by dcb314** [sunqm/libcint#58]
libcint-4.4.0/src/cint3c2e.c:756:1: warning: all paths through this function will call itself [-Winfinite-recursion]

Source code is

void int3c2e_ssc_optimizer(CINTOpt **opt, FINT *atm, FINT natm,
                           FINT *bas, FINT nbas, double *env)
{
        int3c2e_ssc_optimizer(opt, atm, natm, bas, nbas, env);
}

**Comment by sunqm** [comment]
Bug fixed in a621bcd
