### ISSUE TITLE
Defining new operators

### ISSUE THREAD

**Issue by lanieleung** [sunqm/libcint#66]
Hello! I am trying to generate an integral with a 1/r^2 operator. Is there an easy method to generate new operators? Otherwise, is there an existing method I can tweak as a workaround? Thanks in advance.

**Comment by sunqm** [comment]
libcint does not support 1/r^2 operator. I'm not sure how to analytically evaluate integrals of this type. In ECP integral code, I followed the numerical algorithm https://onlinelibrary.wiley.com/doi/10.1002/jcc.20410 . There might be certain analytical algorithms documented in literature for ECP integrals
