### ISSUE TITLE
How to obtain comparable results from Fortran as using python?

### ISSUE THREAD

**Issue by Lancashire3000** [sunqm/libcint#69]
Hi,

  I tried to compare results of `libcint` via loading from `Fortran` and python-pyscf results. Here is my python code （modified from https://pyscf.org/user/gto.html)

```
from pyscf import gto
mol = gto.Mole()
mol.atom = '''O 0 0 0; H  0 1 0; H 0 0 1'''
mol.basis = 'sto-3g'
mol.build()

kin = mol.intor('int1e_kin')
vnuc = mol.intor('int1e_nuc')
overlap = mol.intor('int1e_ovlp')
eri = mol.intor('int2e')

print('kin', kin.shape, kin)
```
What kind of modification in https://github.com/sunqm/libcint/blob/master/examples/fortran_call_cartesian.F90 should I do to obtain comparable results as the above `python` example? Thanks.

**Comment by ndattani** [comment]
I'm just letting people know that this question was also asked here: https://mattermodeling.stackexchange.com/q/8286/5 (in case someone answers there first and doesn't answer here, or the other way around!).

**Comment by sunqm** [comment]
https://github.com/sunqm/libcint/blob/master/examples/python_call_with_pyscf.py
