### ISSUE TITLE
cint1e_ircxp_cart not found

### ISSUE THREAD

**Issue by bruneval** [sunqm/libcint#71]
Dear developers,

I'd like to obtain the integral `cint1e_ircxp_cart` mentioned in the README.md file.

But when linking to libcint 5.1.1, the function cannot be found.
And indeed `nm` does not find it.
```
nm libcint.a | grep rcxp
0000000000007ac0 T cint1e_inuc_rcxp
...
```

Did I do something wrong? in the call? in the compilation?
Thank you for your help.

Best,

Fabien Bruneval
CEA, France

**Comment by sunqm** [comment]
It was renamed to `int1e_cg_irxp_cart`

**Comment by bruneval** [comment]
Thank you. I found it.

Could you just tell the meaning of **cg** in `int1e_cg_irxp_cart`?

And by chance, if there is an up-to-date list of the available functions provided by libcint?

Many thanks.
Fabien

**Comment by sunqm** [comment]
cg is short for common gauge. Integrals are generated by this script. https://github.com/sunqm/libcint/blob/master/scripts/auto_intor.cl . Hope the lisp symbols are readable.

**Comment by bruneval** [comment]
Thank you!

I think everything is clear for me now.
Fabien
