### ISSUE TITLE
integral A^2

### ISSUE THREAD

**Issue by AndyDanian** [sunqm/libcint#73]
Hello, Dear Experts' Libcint

Is it possible implement 

![image](https://user-images.githubusercontent.com/69927647/153921281-212381e5-bf0c-43e0-9329-b45e5a1ffca5.png)

this integral, with Libcint?

Have nice day!

**Comment by sunqm** [comment]
int1e_cg_a11_part_sph (int1e_cg_a11_part_cart) computes the integral for r_K/r_K^3 * r_O. You will receive 9 components in the output buffer. They are orderd as K_xO_x, K_xO_y, K_xO_z, ..., K_zO_y, K_zO_z. Before calling the integral function, you may need to set the common gauge origin `env[PTR_COMMON_ORIG:PTR_COMMON_ORIG+3]` and 1/r origin `env[PTR_RINV_ORIG:PTR_RINV_ORIG+3]` . Definition of PTR_COMMON_ORIG and PTR_RINV_ORIG can be found  https://github.com/sunqm/libcint/blob/master/include/cint.h.in#L29
