### ISSUE TITLE
How to get 3c2e and 2c2e by libcint?

### ISSUE THREAD

**Issue by qw-nb** [sunqm/libcint#75]
I use libint with C to write a program. When I do density, I should calculate integrals like (P|Q) and (ij|P) (2c2e and 3c2e). But i did,'t find this integral in cint.h. In my method, I add a bas with angular=0, exp=0 and comb=1 but this failed. How can I get this integrals?

**Comment by hebrewsnabla** [comment]
You can read pyscf/df/incore.py

There is already 'int3c2e'
