### ISSUE TITLE
Add some more accessible note that the first 20 zeros in env are important.

### ISSUE THREAD

**Issue by MarcusTL12** [sunqm/libcint#76]
It is of course hinted to in the examples and in code using libcint (Fermi.jl, pyscf), but currently the only place I have found an explanation for why those are needed is in issue #70. Having a note about it in the readme or something would help a bit when figuring out how to interface directly with the library.

**Comment by davidsousarj** [comment]
@MarcusTL12  I am trying to implement the integrals from libcint in my program (my program is in fortran and I don't know much about C) and indeed I didn't understand why the pointer of the example starts at 20. I wrote my program with the pointer starting at 1 (fortran indexes are 1-based) and it worked fine so far, at least for the overlap integrals.

I wonder if it would be a problem for my case (I intend to use only cartesian, overlap, kinetic, nuclear and 2e integrals).
