### ISSUE TITLE
The order of  output data for basis with higher angular

### ISSUE THREAD

**Issue by qw-nb** [sunqm/libcint#77]
In libcint's program_ref, it shows for Cartesian GTO with d angular output data is sorted as xx, xy, xz, yy, yz, zz. I want to know how the output data in buf are sorted for Cartesian GTO and real spheric GTO with higher angular momentum as f and g.  Thank you.

**Comment by hebrewsnabla** [comment]
For cartesian AO, it's quite simple to know with this example
```
from pyscf import gto

mol = gto.M(atom='Au .0 .0 0', basis='def2-tzvp', spin=1, cart=True).build()

for i,a in enumerate(mol.ao_labels()):
    print(i,a)
```
For spheric ones, setting `cart=False` will give an order like `f-3, f-2, f-1, f0, f1, ...`. Hope this is what you want, since some other programs also use this notation.
