### ISSUE TITLE
Is there a way to get integrals by basis functions?

### ISSUE THREAD

**Issue by davidsousarj** [sunqm/libcint#82]
Hi, I am trying to implement libcint in a certain old quantum chemistry program which has limited support for integrals (Lmax=2).

As I understand from the example file, libcint calculates blocks of integrals by shell (that is, the all integrals resulting from the combination of the i-th shell with the j-th shell). However my program requires the integrals according to the basis functions (that is, the integral of the i-th basis function with the j-th basis function). Is there any built-in way in libcint to obtain the integrals by basis function?

**Comment by davidsousarj** [comment]
After my question, I was curious to see how PySCF deals with this issue. I'm checking out now the code in `pyscf/gto/moleintor.py`. Maybe there is some clue there to what I should do.

**Comment by davidsousarj** [comment]
I got the answer. PySCF transforms the 1e-integrals from shell-based to AO-based (by basis function) through the `GTOint2c` function in `pyscf/lib/gto/fill_int2c.c`. It seems it is not built-in in libcint, it is a part of PySCF. And unfortunately, it is written in C (I don't know C, just Python and Fortran).

**Comment by hebrewsnabla** [comment]
Although libcint calculates integrals shell by shell, the integrals returned by libcint is always in AO order. For example, if you required overlap intergrals between N AOs, and they belong to K shells, the integrals returned has shape (N,N). There's no shell-based integral actually.

If you calculate integrals batch by batch, you may need to have a map from shell to AO index before calling libcint and tell libcint on which range of shells you want to compute integrals. Then map the returned AO integrals to your desired indices. That's easy.
