### ISSUE TITLE
Building fill_int2c

### ISSUE THREAD

**Issue by alexm-gc** [sunqm/libcint#84]
If I do `pip install pyscf` it builds `fill_int2e` but if I clone this repo and do `mkdir build; cd build; cmake .. ; make` I only get the individual integrals. Does anyone know what I'm doing wrong?

Apologies for any misunderstandings.

**Comment by sunqm** [comment]
fill_int2e is a function of pyscf C extensions. This repo only provides function to compute integrals given a pair, or a triplet, or a quartet of shells
