### ISSUE TITLE
Calling 4c1e integrals

### ISSUE THREAD

**Issue by duykhoidang** [sunqm/libcint#89]
How do you call the 4c1e overlap integral? I see cint4c1e.c in src has something this functionality, but am unsure of what the API call to it will look like. There also doesn't seem to be a way to generate this using clisp.

**Comment by sunqm** [comment]
It has the same API as other integral functions. `cint4c1e_sph(buf, atm, natm, bas, nbas, env);` .  When compiling the library, you need to enable the cmake option `-DWITH_4C1E`
